/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

// #include <react/renderer/components/RTNCenteredTextSpec/Props.h>
#include "Props.h"
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook {
    namespace react {

        ClipPathProps::ClipPathProps(const PropsParserContext &context, const ClipPathProps &sourceProps,
                                     const RawProps &rawProps)
            : ViewProps(context, sourceProps, rawProps),
              color(convertRawProp(context, rawProps, "color", sourceProps.color, {})),
              openClip(convertRawProp(context, rawProps, "openClip", sourceProps.openClip, {})),
              fill(convertRawProp(context, rawProps, "fill", sourceProps.fill, {})),
              stroke(convertRawProp(context, rawProps, "stroke", sourceProps.stroke, {})),
              showProperty(convertRawProp(context, rawProps, "showProperty", sourceProps.showProperty, {})),

              svgKey(convertRawProp(context, rawProps, "svgKey", sourceProps.svgKey, {})),
              d(convertRawProp(context, rawProps, "d", sourceProps.d, {})),
              viewBox(convertRawProp(context, rawProps, "viewBox", sourceProps.viewBox, {})),
              align(convertRawProp(context, rawProps, "align", sourceProps.align, {})),
              aspect(convertRawProp(context, rawProps, "aspect", sourceProps.aspect, {})),
              fillRule(convertRawProp(context, rawProps, "fillRule", sourceProps.fillRule, {})),
              strokeWidth(convertRawProp(context, rawProps, "strokeWidth", sourceProps.strokeWidth, {})),
              strokeCap(convertRawProp(context, rawProps, "strokeCap", sourceProps.strokeCap, {})),
              strokeJoin(convertRawProp(context, rawProps, "strokeJoin", sourceProps.strokeJoin, {})),
              strokeMiter(convertRawProp(context, rawProps, "strokeMiter", sourceProps.strokeMiter, {})),
              strokeStart(convertRawProp(context, rawProps, "strokeStart", sourceProps.strokeStart, {})),
              strokeEnd(convertRawProp(context, rawProps, "strokeEnd", sourceProps.strokeEnd, {})),

              translateZ(convertRawProp(context, rawProps, "translateZ", sourceProps.translateZ, {})),
              transX(convertRawProp(context, rawProps, "transX", sourceProps.transX, {})),
              transY(convertRawProp(context, rawProps, "transY", sourceProps.transY, {})),
              transPercentageValue(
                  convertRawProp(context, rawProps, "transPercentageValue", sourceProps.transPercentageValue, {})),
              rot(convertRawProp(context, rawProps, "rot", sourceProps.rot, {})),
              rotO(convertRawProp(context, rawProps, "rotO", sourceProps.rotO, {})),
              rotOx(convertRawProp(context, rawProps, "rotOx", sourceProps.rotOx, {})),
              rotOy(convertRawProp(context, rawProps, "rotOy", sourceProps.rotOy, {})),
              rotPercentageValue(
                  convertRawProp(context, rawProps, "rotPercentageValue", sourceProps.rotPercentageValue, {})),
              sc(convertRawProp(context, rawProps, "sc", sourceProps.sc, {})),
              scX(convertRawProp(context, rawProps, "scX", sourceProps.scX, {})),
              scY(convertRawProp(context, rawProps, "scY", sourceProps.scY, {})),
              scO(convertRawProp(context, rawProps, "scO", sourceProps.scO, {})),
              scOx(convertRawProp(context, rawProps, "scOx", sourceProps.scOx, {})),
              scOy(convertRawProp(context, rawProps, "scOy", sourceProps.scOy, {})),
              scPercentageValue(
                  convertRawProp(context, rawProps, "scPercentageValue", sourceProps.scPercentageValue, {}))

        {}
    } // namespace react
} // namespace facebook