
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeCpp.js
 */

// #include <react/renderer/components/RTNCenteredTextSpec/ShadowNodes.h>
#include "ShadowNodes.h"

namespace facebook {
namespace react {

extern const char ClipPathComponentName[] = "ClipPath";

} // namespace react
} // namespace facebook
